"use strict";var userAgent=navigator.userAgent.toLowerCase(),initialDate=new Date(),$document=$(document),$window=$(window),$html=$("html"),isDesktop=$html.hasClass("desktop"),isIE=userAgent.indexOf("msie")!=-1?parseInt(userAgent.split("msie")[1]):userAgent.indexOf("trident")!=-1?11:userAgent.indexOf("edge")!=-1?12:false,isMobile=/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent),isTouch="ontouchstart"in window,plugins={pointerEvents:isIE<11?"js/pointer-events.min.js":false,smoothScroll:$html.hasClass("use--smoothscroll")?"js/smoothscroll.min.js":false,bootstrapTooltip:$("[data-toggle='tooltip']"),bootstrapTabs:$(".tabs"),rdParallax:$(".rd-parallax"),rdAudioPlayer:$(".rd-audio"),fullPage:$(".page-scroller"),rdVideoPlayer:$(".rd-video-player"),responsiveTabs:$(".responsive-tabs"),rdGoogleMaps:$(".rd-google-map"),rdNavbar:$(".rd-navbar"),rdVideoBG:$(".rd-video"),rdRange:$('.rd-range'),textRotator:$(".text-rotator"),owl:$(".owl-carousel"),swiper:$(".swiper-slider"),counter:$(".counter"),flickrfeed:$(".flickr"),twitterfeed:$(".twitter"),progressBar:$(".progress-bar-js"),progressLinear:$(".progress-linear"),isotope:$(".isotope"),countDown:$(".countdown"),calendar:$(".rd-calendar"),facebookfeed:$(".facebook"),instafeed:$(".instafeed"),facebookWidget:$('#fb-root'),materialTabs:$('.rd-material-tabs'),filePicker:$('.rd-file-picker'),fileDrop:$('.rd-file-drop'),popover:$('[data-toggle="popover"]'),dateCountdown:$('.DateCountdown'),statefulButton:$('.btn-stateful'),slick:$('.slick-slider'),scroller:$(".scroll-wrap"),socialite:$(".socialite"),viewAnimate:$('.view-animate'),selectFilter:$("select"),rdInputLabel:$(".form-label"),stacktable:$("[data-responsive=true]"),bootstrapDateTimePicker:$("[data-time-picker]"),customWaypoints:$('[data-custom-scroll-to]'),photoSwipeGallery:$("[data-photo-swipe-item]"),circleProgress:$(".progress-bar-circle"),stepper:$("input[type='number']"),radio:$("input[type='radio']"),checkbox:$("input[type='checkbox']"),customToggle:$("[data-custom-toggle]"),rdMailForm:$(".rd-mailform"),regula:$("[data-constraints]"),search:$(".rd-search"),searchResults:$('.rd-search-results'),imgZoom:$('[mag-thumb]')};$window.load(function(){$('html').addClass('page-loaded');});$document.ready(function(){function getSwiperHeight(object,attr){var val=object.attr("data-"+ attr),dim;if(!val){return undefined;}
dim=val.match(/(px)|(%)|(vh)$/i);if(dim.length){switch(dim[0]){case"px":return parseFloat(val);case"vh":return $(window).height()*(parseFloat(val)/ 100);
case"%":return object.width()*(parseFloat(val)/ 100);
}}else{return undefined;}}
function toggleSwiperCaptionAnimation(swiper){var prevSlide=$(swiper.container),nextSlide=$(swiper.slides[swiper.activeIndex]);prevSlide.find("[data-caption-animate]").each(function(){var $this=$(this);$this.removeClass("animated").removeClass($this.attr("data-caption-animate")).addClass("not-animated");});nextSlide.find("[data-caption-animate]").each(function(){var $this=$(this),delay=$this.attr("data-caption-delay"),duration=$this.attr('data-caption-duration');setTimeout(function(){$this.removeClass("not-animated").addClass($this.attr("data-caption-animate")).addClass("animated");if(duration){$this.css('animation-duration',duration+'ms');}},delay?parseInt(delay):0);});}
function makeParallax(el,speed,wrapper,prevScroll){var scrollY=window.scrollY||window.pageYOffset;if(prevScroll!=scrollY){prevScroll=scrollY;el.addClass('no-transition');el[0].style['transform']='translate3d(0,'+-scrollY*(1- speed)+'px,0)';el.height();el.removeClass('no-transition');if(el.attr('data-fade')==='true'){var bound=el[0].getBoundingClientRect(),offsetTop=bound.top*2+ scrollY,sceneHeight=wrapper.outerHeight(),sceneDevider=wrapper.offset().top+ sceneHeight/2.0,layerDevider=offsetTop+ el.outerHeight()/ 2.0,
pos=sceneHeight/6.0,opacity;if(sceneDevider+ pos>layerDevider&&sceneDevider- pos<layerDevider){el[0].style["opacity"]=1;}else{if(sceneDevider- pos<layerDevider){opacity=1+((sceneDevider+ pos- layerDevider)/ sceneHeight / 3.0 * 5);
}else{opacity=1-((sceneDevider- pos- layerDevider)/ sceneHeight / 3.0 * 5);
}
el[0].style["opacity"]=opacity<0?0:opacity>1?1:opacity.toFixed(2);}}}
requestAnimationFrame(function(){makeParallax(el,speed,wrapper,prevScroll);});}
function isScrolledIntoView(elem){var $window=$(window);return elem.offset().top+ elem.outerHeight()>=$window.scrollTop()&&elem.offset().top<=$window.scrollTop()+ $window.height();}
function lazyInit(element,func){var $win=jQuery(window);$win.on('load scroll',function(){if((!element.hasClass('lazy-loaded')&&(isScrolledIntoView(element)))){func.call();element.addClass('lazy-loaded');}});}
function initBootstrapTooltip(tooltipPlacement){if(window.innerWidth<599){plugins.bootstrapTooltip.tooltip('destroy');plugins.bootstrapTooltip.tooltip({placement:'bottom'});}else{plugins.bootstrapTooltip.tooltip('destroy');plugins.bootstrapTooltip.tooltipPlacement;plugins.bootstrapTooltip.tooltip();}}
function changeExternalButtons(respTabItem,direction){var prev,next,activeItem;respTabItem.find('.resp-tabs-extertal-list li').removeClass('active');activeItem=respTabItem.find('.resp-tab-item.resp-tab-active');next=activeItem.next();if(!next.length){next=respTabItem.find('.resp-tab-item:first-child()');}
prev=activeItem.prev();if(!prev.length){prev=respTabItem.find('.resp-tab-item:last-child()');}
if(direction){if(direction==='next'){next.trigger('click');}else{prev.trigger('click');}
setTimeout(function(){changeExternalButtons(respTabItem);},10);}
respTabItem.find('.resp-tab-external-prev li:nth-child('+(prev.index()+ 1)+')').addClass('active');respTabItem.find('.resp-tab-external-next li:nth-child('+(next.index()+ 1)+')').addClass('active');}
var o=$("#copyright-year");if(o.length){o.text(initialDate.getFullYear());}
if(isIE){if(isIE<10){$html.addClass("lt-ie-10");}
if(isIE<11){if(plugins.pointerEvents){$.getScript(plugins.pointerEvents).done(function(){$html.addClass("ie-10");PointerEventsPolyfill.initialize({});});}}
if(isIE===11){$("html").addClass("ie-11");}
if(isIE===12){$("html").addClass("ie-edge");}}
if(plugins.bootstrapTooltip.length){var tooltipPlacement=plugins.bootstrapTooltip.attr('data-placement');initBootstrapTooltip(tooltipPlacement);$(window).on('resize orientationchange',function(){initBootstrapTooltip(tooltipPlacement);})}
if(plugins.smoothScroll){$.getScript(plugins.smoothScroll);}
if(plugins.rdAudioPlayer.length>0){var i;for(i=0;i<plugins.rdAudioPlayer.length;i++){$(plugins.rdAudioPlayer[i]).RDAudio();}}
if(plugins.textRotator.length){var i;for(i=0;i<plugins.textRotator.length;i++){var textRotatorItem=plugins.textRotator[i];$(textRotatorItem).rotator();}}
if(isDesktop){$().UItoTop({easingType:'easeOutQuart',containerClass:'ui-to-top fa fa-angle-up'});}
if(plugins.viewAnimate.length){var i;for(i=0;i<plugins.viewAnimate.length;i++){var $view=$(plugins.viewAnimate[i]).not('.active');$document.on("scroll",$.proxy(function(){if(isScrolledIntoView(this)){this.addClass("active");}},$view)).trigger("scroll");}}
if(plugins.fullPage.length){var isFullPage=true;plugins.fullPage.fullpage({navigation:true,navigationPosition:'right',responsiveWidth:1201,scrollOverflow:true,sectionSelector:'.scrollerSection',scrollBar:true});$window.on('resize',function(e){if(window.innerWidth<1199&&isFullPage){$.fn.fullpage.destroy('all');isFullPage=false;}
if(window.innerWidth>=1200&&!isFullPage){plugins.fullPage.fullpage({navigation:true,navigationPosition:'right',responsiveWidth:1201,scrollOverflow:true,sectionSelector:'.scrollerSection',scrollBar:true,});isFullPage=true;}});$window.trigger('resize');}
if(plugins.rdNavbar.length){plugins.rdNavbar.RDNavbar({anchorNavSpeed:700,anchorNavOffset:-10,stickUpClone:true,anchorNavEasing:'easeInOutQuart',});if(plugins.rdNavbar.attr("data-body-class")){document.body.className+=' '+ plugins.rdNavbar.attr("data-body-class");}}
if(plugins.swiper.length){var i;for(i=0;i<plugins.swiper.length;i++){var s=$(plugins.swiper[i]);var pag=s.find(".swiper-pagination"),next=s.find(".swiper-button-next"),prev=s.find(".swiper-button-prev"),bar=s.find(".swiper-scrollbar"),parallax=s.parents('.rd-parallax').length,swiperSlide=s.find(".swiper-slide");for(j=0;j<swiperSlide.length;j++){var $this=$(swiperSlide[j]),url;if(url=$this.attr("data-slide-bg")){$this.css({"background-image":"url("+ url+")","background-size":"cover"})}}
swiperSlide.end().find("[data-caption-animate]").addClass("not-animated").end().swiper({autoplay:s.attr('data-autoplay')?s.attr('data-autoplay')==="false"?undefined:s.attr('data-autoplay'):5000,effect:s.attr('data-slide-effect')?s.attr('data-slide-effect'):"slide",speed:s.attr('data-slide-speed')?s.attr('data-slide-speed'):600,keyboardControl:s.attr('data-keyboard')==="true",mousewheelReleaseOnEdges:s.attr('data-mousewheel-release')==="true",nextButton:next.length?next.get(0):null,prevButton:prev.length?prev.get(0):null,pagination:pag.length?pag.get(0):null,paginationClickable:pag.length?pag.attr("data-clickable")!=="false":false,paginationBulletRender:pag.length?pag.attr("data-index-bullet")==="true"?function(index,className){return'<span class="'+ className+'">'+(index+ 1)+'</span>';}:null:null,scrollbar:bar.length?bar.get(0):null,scrollbarDraggable:bar.length?bar.attr("data-draggable")!=="false":true,scrollbarHide:bar.length?bar.attr("data-draggable")==="false":false,direction:'vertical',slidesPerView:1,mousewheelControl:true,simulateTouch:s.attr('data-simulate-touch')?s.attr('data-simulate-touch')==="true":false,onTransitionStart:function(swiper){toggleSwiperInnerVideos(swiper);},onTransitionEnd:function(swiper){toggleSwiperCaptionAnimation(swiper);},onInit:function(swiper){toggleSwiperInnerVideos(swiper);toggleSwiperCaptionAnimation(swiper);var swiperParalax=s.find(".swiper-parallax");for(var k=0;k<swiperParalax.length;k++){var $this=$(swiperParalax[k]),speed;if(parallax&&!isIEBrows&&!isMobile){if(speed=$this.attr("data-speed")){makeParallax($this,speed,s,false);}}}
$(window).on('resize',function(){swiper.update(true);})}});$(window).on("resize",function(){var mh=getSwiperHeight(s,"min-height"),h=getSwiperHeight(s,"height");if(h){s.css("height",mh?mh>h?mh:h:h);}}).trigger("resize");}}
if(plugins.search.length||plugins.searchResults){var handler="bat/rd-search.php";var defaultTemplate='<h5 class="search_title"><a target="_top" href="#{href}" class="search_link">#{title}</a></h5>'+'<p>...#{token}...</p>'+'<p class="match"><em>Terms matched: #{count} - URL: #{href}</em></p>';var defaultFilter='*.html';if(plugins.search.length){for(i=0;i<plugins.search.length;i++){var searchItem=$(plugins.search[i]),options={element:searchItem,filter:(searchItem.attr('data-search-filter'))?searchItem.attr('data-search-filter'):defaultFilter,template:(searchItem.attr('data-search-template'))?searchItem.attr('data-search-template'):defaultTemplate,live:(searchItem.attr('data-search-live'))?searchItem.attr('data-search-live'):false,liveCount:(searchItem.attr('data-search-live-count'))?parseInt(searchItem.attr('data-search-live')):4,current:0,processed:0,timer:{}};if($('.rd-navbar-search-toggle').length){var toggle=$('.rd-navbar-search-toggle');toggle.on('click',function(){if(!($(this).hasClass('active'))){searchItem.find('input').val('').trigger('propertychange');}});}
if(options.live){var clearHandler=false;searchItem.find('input').on("keyup input propertychange",$.proxy(function(){this.term=this.element.find('input').val().trim();this.spin=this.element.find('.input-group-addon');clearTimeout(this.timer);if(this.term.length>2){this.timer=setTimeout(liveSearch(this),200);if(clearHandler==false){clearHandler=true;$("body").on("click",function(e){if($(e.toElement).parents('.rd-search').length==0){$('#rd-search-results-live').addClass('cleared').html('');}})}}else if(this.term.length==0){$('#'+ this.live).addClass('cleared').html('');}},options,this));}
searchItem.submit($.proxy(function(){$('<input />').attr('type','hidden').attr('name',"filter").attr('value',this.filter).appendTo(this.element);return true;},options,this))}}
if(plugins.searchResults.length){var regExp=/\?.*s=([^&]+)\&filter=([^&]+)/g;var match=regExp.exec(location.search);if(match!=null){$.get(handler,{s:decodeURI(match[1]),dataType:"html",filter:match[2],template:defaultTemplate,live:''},function(data){plugins.searchResults.html(data);})}}}
if(plugins.slick.length){var i;for(i=0;i<plugins.slick.length;i++){var $slickItem=$(plugins.slick[i]);$slickItem.slick({slidesToScroll:parseInt($slickItem.attr('data-slide-to-scroll'))||1,asNavFor:$slickItem.attr('data-for')||false,dots:$slickItem.attr("data-dots")=="true",infinite:$slickItem.attr("data-loop")=="true",focusOnSelect:true,arrows:$slickItem.attr("data-arrows")=="true",swipe:$slickItem.attr("data-swipe")=="true",autoplay:$slickItem.attr("data-autoplay")=="true",vertical:$slickItem.attr("data-vertical")=="true",centerMode:$slickItem.attr("data-center-mode")=="true",centerPadding:$slickItem.attr("data-center-padding")?$slickItem.attr("data-center-padding"):'0.50',mobileFirst:true,responsive:[{breakpoint:0,settings:{slidesToShow:parseInt($slickItem.attr('data-items'))||1,}},{breakpoint:480,settings:{slidesToShow:parseInt($slickItem.attr('data-xs-items'))||1,}},{breakpoint:768,settings:{slidesToShow:parseInt($slickItem.attr('data-sm-items'))||1,}},{breakpoint:992,settings:{slidesToShow:parseInt($slickItem.attr('data-md-items'))||1,}},{breakpoint:1200,settings:{slidesToShow:parseInt($slickItem.attr('data-lg-items'))||1,}}]}).on('afterChange',function(event,slick,currentSlide,nextSlide){var $this=$(this),childCarousel=$this.attr('data-child');if(childCarousel){$(childCarousel+' .slick-slide').removeClass('slick-current');$(childCarousel+' .slick-slide').eq(currentSlide).addClass('slick-current');}});}}
if(plugins.owl.length){var i;for(i=0;i<plugins.owl.length;i++){var c=$(plugins.owl[i]),responsive={};var aliaces=["-","-xs-","-sm-","-md-","-lg-"],values=[0,480,768,992,1200],j,k;for(j=0;j<values.length;j++){responsive[values[j]]={};for(k=j;k>=-1;k--){if(!responsive[values[j]]["items"]&&c.attr("data"+ aliaces[k]+"items")){responsive[values[j]]["items"]=k<0?1:parseInt(c.attr("data"+ aliaces[k]+"items"));}
if(!responsive[values[j]]["stagePadding"]&&responsive[values[j]]["stagePadding"]!==0&&c.attr("data"+ aliaces[k]+"stage-padding")){responsive[values[j]]["stagePadding"]=k<0?0:parseInt(c.attr("data"+ aliaces[k]+"stage-padding"));}
if(!responsive[values[j]]["margin"]&&responsive[values[j]]["margin"]!==0&&c.attr("data"+ aliaces[k]+"margin")){responsive[values[j]]["margin"]=k<0?30:parseInt(c.attr("data"+ aliaces[k]+"margin"));}}}
c.owlCarousel({autoplay:c.attr("data-autoplay")==="true",loop:c.attr("data-loop")!=="false",items:1,dotsContainer:c.attr("data-pagination-class")||false,navContainer:c.attr("data-navigation-class")||false,mouseDrag:c.attr("data-mouse-drag")!=="false",nav:c.attr("data-nav")==="true",dots:c.attr("data-dots")==="true",dotsEach:c.attr("data-dots-each")?parseInt(c.attr("data-dots-each")):false,responsive:responsive,smartSpeed:1000,navText:[]});}}
if(plugins.counter.length){var i;for(i=0;i<plugins.counter.length;i++){var $counterNotAnimated=$(plugins.counter[i]).not('.animated');$document.on("scroll",$.proxy(function(){var $this=this;if((!$this.hasClass("animated"))&&(isScrolledIntoView($this))){$this.countTo({refreshInterval:40,speed:$this.attr("data-speed")||1000});$this.addClass('animated');}},$counterNotAnimated)).trigger("scroll");}}
if(plugins.isotope.length){var i,isogroup=[];for(i=0;i<plugins.isotope.length;i++){var isotopeItem=plugins.isotope[i],iso=new Isotope(isotopeItem,{itemSelector:'.isotope-item',layoutMode:isotopeItem.getAttribute('data-isotope-layout')?isotopeItem.getAttribute('data-isotope-layout'):'masonry',filter:'*'});isogroup.push(iso);}
$(window).on('load',function(){setTimeout(function(){var i;for(i=0;i<isogroup.length;i++){isogroup[i].element.className+=" isotope--loaded";isogroup[i].layout();}},600);});var resizeTimout;$("[data-isotope-filter]").on("click",function(e){e.preventDefault();var filter=$(this);clearTimeout(resizeTimout);filter.parents(".isotope-filters").find('.active').removeClass("active");filter.addClass("active");var iso=$('.isotope[data-isotope-group="'+ this.getAttribute("data-isotope-group")+'"]');iso.isotope({itemSelector:'.isotope-item',layoutMode:iso.attr('data-isotope-layout')?iso.attr('data-isotope-layout'):'masonry',filter:this.getAttribute("data-isotope-filter")=='*'?'*':'[data-filter*="'+ this.getAttribute("data-isotope-filter")+'"]'});}).eq(0).trigger("click")}
if(isDesktop&&$html.hasClass("wow-animation")&&$(".wow").length){new WOW().init();}
if(plugins.bootstrapTabs.length){var i;for(i=0;i<plugins.bootstrapTabs.length;i++){var bootstrapTabsItem=$(plugins.bootstrapTabs[i]);bootstrapTabsItem.on("click","a",function(event){event.preventDefault();$(this).tab('show');});}}
if(plugins.scroller.length){var i;for(i=0;i<plugins.scroller.length;i++){var scrollerItem=$(plugins.scroller[i]);scrollerItem.mCustomScrollbar({scrollInertia:200,scrollButtons:{enable:true}});}}
if(plugins.photoSwipeGallery.length){$document.delegate("[data-photo-swipe-item]","click",function(event){event.preventDefault();var $el=$(this),$galleryItems=$el.parents("[data-photo-swipe-gallery]").find("a[data-photo-swipe-item]"),pswpElement=document.querySelectorAll('.pswp')[0],encounteredItems={},pswpItems=[],options,pswpIndex=0,pswp;if($galleryItems.length==0){$galleryItems=$el;}
$galleryItems.each(function(){var $item=$(this),src=$item.attr('href'),size=$item.attr('data-size').split('x'),pswdItem;if($item.is(':visible')){if(!encounteredItems[src]){pswdItem={src:src,w:parseInt(size[0],10),h:parseInt(size[1],10),el:$item};encounteredItems[src]={item:pswdItem,index:pswpIndex};pswpItems.push(pswdItem);pswpIndex++;}}});options={index:encounteredItems[$el.attr('href')].index,getThumbBoundsFn:function(index){var $el=pswpItems[index].el,offset=$el.offset();return{x:offset.left,y:offset.top,w:$el.width()};}};pswp=new PhotoSwipe(pswpElement,PhotoSwipeUI_Default,pswpItems,options);pswp.init();});}
if(plugins.stacktable.length){var i;for(i=0;i<plugins.stacktable.length;i++){var stacktableItem=$(plugins.stacktable[i]);stacktableItem.stacktable();}}
if(plugins.customToggle.length){var i;for(i=0;i<plugins.customToggle.length;i++){var $this=$(plugins.customToggle[i]);$this.on('click',$.proxy(function(event){event.preventDefault();var $ctx=$(this);$($ctx.attr('data-custom-toggle')).add(this).toggleClass('active');},$this));if($this.attr("data-custom-toggle-disable-on-blur")==="true"){$("body").on("click",$this,function(e){if(e.target!==e.data[0]&&$(e.data.attr('data-custom-toggle')).find($(e.target)).length==0&&e.data.find($(e.target)).length==0){$(e.data.attr('data-custom-toggle')).add(e.data[0]).removeClass('active');}})}}}
if(plugins.imgZoom.length){var i;for(i=0;i<plugins.imgZoom.length;i++){var $imgZoomItem=$(plugins.imgZoom[i]);$imgZoomItem.mag();}}
if(plugins.customWaypoints.length){var i;for(i=0;i<plugins.customWaypoints.length;i++){var $this=$(plugins.customWaypoints[i]);$this.on('click',function(e){e.preventDefault();$("body, html").stop().animate({scrollTop:$("#"+ $(this).attr('data-custom-scroll-to')).offset().top},1000,function(){$(window).trigger("resize");});});}}
if(plugins.rdParallax.length){var i;$.RDParallax();if(!isIE&&!isMobile){$(window).on("scroll",function(){for(i=0;i<plugins.rdParallax.length;i++){var parallax=$(plugins.rdParallax[i]);if(isScrolledIntoView(parallax)){parallax.find(".rd-parallax-inner").css("position","fixed");}else{parallax.find(".rd-parallax-inner").css("position","absolute");}}});}
$("a[href='#'], a[href^='#']").on("click",function(event){setTimeout(function(){$(window).trigger("resize");},300);});}});
